import uvicorn
from fastapi import FastAPI, Query
from playwright.async_api import async_playwright
from contextlib import asynccontextmanager
import asyncio
import os
import re
import json
import time
import uuid

app = FastAPI()

# --- Global Session Manager ---
class BrowserSession:
    def __init__(self):
        self.playwright = None
        self.browser = None
        self.context = None
        self.page = None
        self.is_ready = False
        self.bot_id = "25874" # Gemini ID

session = BrowserSession()

def log(text):
    print(f"[LOG] {text}", flush=True)

def clean_response(text):
    """
    Ye function response me se 'Thinking' process ko nikal kar
    sirf final saaf jawab return karta hai.
    """
    if not text: return ""

    # 1. Remove <think> tags content (DeepSeek style)
    # Ye <think> se le kar </think> tak sab kuch uda dega
    cleaned = re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL)

    # 2. Remove "Thinking..." lines (Agar shuru me hon)
    cleaned = re.sub(r'^Thinking\.\.\.\s*', '', cleaned, flags=re.DOTALL)
    
    # 3. Remove lines staring with "Generated by..." if any
    cleaned = re.sub(r'Generated by .*?\n', '', cleaned, flags=re.IGNORECASE)

    # 4. Strip extra whitespace
    return cleaned.strip()

async def close_browser():
    log("🔴 KILLING BROWSER SESSION...")
    try:
        if session.page: await session.page.close()
        if session.context: await session.context.close()
        if session.browser: await session.browser.close()
        if session.playwright: await session.playwright.stop()
    except:
        pass
    session.is_ready = False

async def init_browser():
    if session.is_ready:
        return

    log("🔵 INITIALIZING NEW FRESH BROWSER...")
    try:
        session.playwright = await async_playwright().start()
        
        session.browser = await session.playwright.chromium.launch(
            headless=True,
            args=[
                "--no-sandbox",
                "--disable-setuid-sandbox",
                "--disable-blink-features=AutomationControlled",
                "--disable-infobars",
                "--disable-dev-shm-usage"
            ]
        )
        
        session.context = await session.browser.new_context(
            user_agent="Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Mobile Safari/537.36"
        )
        
        session.page = await session.context.new_page()

        # Stealth Mode
        await session.page.add_init_script("Object.defineProperty(navigator, 'webdriver', { get: () => undefined });")
        
        session.page.on("console", lambda msg: print(f"[BROWSER] {msg.text}"))

        log("   👉 Loading DeepAI Homepage...")
        await session.page.goto("https://deepai.org/chat", timeout=90000, wait_until="domcontentloaded")
        
        log("   ✅ DeepAI Loaded!")
        session.is_ready = True

    except Exception as e:
        log(f"   ❌ Init Failed: {e}")
        await close_browser()

@asynccontextmanager
async def lifespan(app: FastAPI):
    await init_browser()
    yield
    await close_browser()

app = FastAPI(lifespan=lifespan)

async def send_deepai_message(message):
    if not session.is_ready:
        await init_browser()

    log(f"🚀 Processing Message: {message}")

    js_script = """
    async (userMessage) => {
        try {
            console.log("Generating Key...");
            const apiKey = generateTryitApiKey(); 

            const formData = new FormData();
            formData.append('chat_style', 'chat');
            // History me sirf user ka message daal rahe hain taake fresh response aye
            // (Go code already history manage kar raha hai prompt me)
            formData.append('chatHistory', JSON.stringify([{ role: "user", content: userMessage }]));
            
            // Model: Gemini 2.5 Flash Lite
            formData.append('model', 'gemini-2.5-flash-lite'); 
            
            formData.append('hacker_is_stinky', 'very_stinky');
            formData.append('enabled_tools', JSON.stringify(["image_generator","image_editor"]));

            console.log("Sending Fetch...");
            const response = await fetch('https://api.deepai.org/hacking_is_a_serious_crime', {
                method: 'POST',
                headers: { 'api-key': apiKey },
                body: formData
            });

            if (response.status !== 200) {
                return { error: true, status: response.status, body: await response.text() };
            }

            // Stream Handling: Wait until full response is received
            const reader = response.body.getReader();
            const decoder = new TextDecoder();
            let fullText = "";

            while (true) {
                const { done, value } = await reader.read();
                if (done) break;
                fullText += decoder.decode(value, { stream: true });
            }
            
            // Yahan hum browser ke andar hi kuch nahi kar rahe, 
            // Sara raw text Python ko bhej rahe hain taake Python cleaning kare.
            return { success: true, text: fullText };

        } catch (err) {
            return { error: true, message: err.toString() };
        }
    }
    """

    try:
        # 1. Execute JS
        result = await session.page.evaluate(js_script, message)
        
        # 2. Handle Errors
        if result.get("error"):
            log(f"   ❌ JS Error: {result}")
            if result.get("status") in [401, 403] or "login" in str(result.get("body", "")).lower():
                raise Exception("Session Expired")
            return f"Error: {result}"
        
        raw_text = result.get('text', '')
        log(f"   📦 Raw Length: {len(raw_text)}")
        
        # 3. CLEANING PROCESS (Yahan Thinking remove hogi)
        final_cleaned_text = clean_response(raw_text)
        
        log(f"   ✨ Cleaned Length: {len(final_cleaned_text)}")
        return final_cleaned_text

    except Exception as e:
        log(f"⚠️ Exception: {e}")
        raise e

@app.get("/chat")
async def chat_endpoint(message: str = Query(..., description="User message")):
    try:
        reply = await send_deepai_message(message)
        return {"response": reply, "status": "success"}
    
    except Exception as e:
        log("🔄 Session Failed. Restarting...")
        await close_browser()
        await init_browser()
        
        try:
            reply = await send_deepai_message(message)
            return {"response": reply, "status": "success"}
        except Exception as final_e:
            return {"error": str(final_e), "status": "failed"}

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8080))
    uvicorn.run(app, host="0.0.0.0", port=port)
